# -*- coding: utf-8 -*-
import yaml
import sys
import relationship
from relationship import Relationship

"""
This script generates a file in the backend based on the relationships defined
in the OpenAPI specification.

The mapping is the following:

  (parent resource, embedding name) -> embedded resource full name

This is used by the backend to resolve the correct scope when checking embed
permissions. For example, calling

  /controllable_unit_service_provider?embed=service_provider

should check the scope read:data:party, not read:data:service_provider, because
the embedded resource is actually the party table.
"""


def build_embed_mapping(rels: list[Relationship]) -> dict[str, dict[str, str]]:
    embed_mapping = {}
    for rel in rels:
        parent_resource = rel.child.resource
        embed_name = rel.name
        actual_resource = rel.parent.resource
        if parent_resource not in embed_mapping:
            embed_mapping[parent_resource] = {}
        embed_mapping[parent_resource][embed_name] = actual_resource
    return embed_mapping


def render_go(embed_mapping):
    print("// code generated by openapi_to_embed_relations.py -- DO NOT EDIT\n")
    print("package data\n")
    print("var embedRelations = map[string]map[string]string{")

    for parent_resource in sorted(embed_mapping):
        print(f'\t"{parent_resource}": {{')
        for embed_name in sorted(embed_mapping[parent_resource]):
            actual = embed_mapping[parent_resource][embed_name]
            print(f'\t\t"{embed_name}": "{actual}",')
        print("\t},")

    print("}")


if __name__ == "__main__":
    data = yaml.safe_load(sys.stdin)
    resources = data["resources"]

    rels = relationship.collect(resources)
    embed_mapping = build_embed_mapping(rels)

    render_go(embed_mapping)
