@startuml attachment_download_sequence
!theme plain

title Attachment Download Sequence

skinparam LifelineStrategy solid
skinparam SequenceMessageAlign direction

participant User as user
participant "FIS" as fis
participant Bucket as bucket

user -> fis: ""GET /res_attachment/<color #d58000>19</color>/download""
activate fis #d6e4d5
activate user #d6e4d5

fis -> fis: Get metadata for attachment <color #d58000>19</color>
rnote right of fis
""<color #886599>object_id</color>"", ""<color #05677d>filename_sanitised</color>""
end note

fis -> bucket:\
Get presigned download URL for ""attachment/<color #886599>object_id</color>/<color #05677d>filename_sanitised</color>""\n\
(with credentials for bucket)
activate bucket #d6e4d5

bucket -> fis: ""200 OK""
rnote left of bucket
""<color #886599>url</color>"", valid for 1 minute
end note
deactivate bucket

fis -> user:\
""301 Moved Permanently""\n\
Redirect to ""<color #886599>url</color>""
deactivate fis

user -> bucket: ""GET <color #886599>url</color>""
activate bucket #d6e4d5
bucket -> user: ""200 OK""
deactivate bucket
deactivate user
rnote left of bucket
File contents
""Content-Disposition: attachment; filename=<color #05677d>filename</color>""
(the browser <i>downloads</i> the file, with the original name given by the user)
end note

@enduml
