@startuml oidc_logout_sequence

!theme plain

title OpenID Connect Logout Flow

autonumber
autoactivate on

skinparam note {
    BackgroundColor #FFFFBD
}

actor "User Agent\n(Browser)" as UA
activate UA
participant "Frontend Portal" as PORTAL
participant "Identity Provider" as IDP
participant "Flexibility\nInformation System (FIS)\nAuth API" as AUTH
participant "Database" as DB

UA -> PORTAL: Click logout
return Go to /auth/v0/logout
UA -> AUTH: Navigate to /auth/v0/logout
AUTH -> DB: Invalidate session
return
return HTTP 302 Redirect to Identity Provider\nUnset <:cookie:> flex_session

UA -> IDP: Follow redirect\nGET /logout?post_logout_redirect_uri=<login url>
note over IDP
    Identity provider does logout
    and terminates sessions.
end note
return HTTP 302 Redirect to redirect uri

UA -> PORTAL: Follow redirect\nGET /#/login
return Welcome page

note over PORTAL
    User is now ready to log in again.
end note

@enduml
