config:
  validation: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  FunctionMaxLength:
    active: false

style:
  MaxLineLength:
    maxLineLength: 160
    excludeRawStrings: true
  CascadingCallWrapping:
    active: false
  MultilineRawStringIndentation:
    active: false
  ReturnCount:
    active: false

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 12
