[tools]
"python" = "3.14.6"
"go" = "1.26.5"
"uv" = "0.11.29"
"golangci-lint" = "2.12.2"
"pandoc" = "3.10"
"ruff" = "0.15.22"
"sqlc" = "1.31.1"

"go:github.com/google/go-licenses/v2" = "2.0.1"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.5.0"
"go:golang.org/x/tools/cmd/stringer" = "0.47.0"
"go:github.com/dmarkham/enumer" = "1.6.3"
"go:github.com/air-verse/air" = "1.65.3"

[settings]
python.uv_venv_auto = "create|source"

[env]
GOEXPERIMENT = 'jsonv2'
REQUESTS_CA_BUNDLE = '/etc/ssl/certs/ca-certificates.crt'
