// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiAccountingPoint struct {
	ID               int
	BusinessID       string
	SystemOperatorID int
	RecordedBy       int
	RecordedAt       pgtype.Timestamptz
}

type ApiAccountingPointBalanceResponsibleParty struct {
	AccountingPointID         int
	BalanceResponsiblePartyID int
	EnergyDirection           string
	ValidFrom                 pgtype.Timestamptz
	ValidTo                   pgtype.Timestamptz
}

type ApiAccountingPointEnergySupplier struct {
	AccountingPointID int
	EnergySupplierID  int
	ValidFrom         pgtype.Timestamptz
	ValidTo           pgtype.Timestamptz
}

type ApiControllableUnit struct {
	ID                       int
	BusinessID               string
	Name                     string
	StartDate                pgtype.Date
	Status                   string
	RegulationDirection      string
	MaximumAvailableCapacity float64
	IsSmall                  bool
	MinimumDuration          *int
	MaximumDuration          *int
	RecoveryDuration         *int
	RampRate                 *float64
	AccountingPointID        int
	GridNodeID               *string
	GridValidationStatus     string
	GridValidationNotes      *string
	ValidatedAt              pgtype.Timestamptz
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
}

type ApiControllableUnitHistory struct {
	ControllableUnitID       int
	ID                       int
	BusinessID               string
	Name                     string
	StartDate                pgtype.Date
	Status                   string
	RegulationDirection      string
	MaximumAvailableCapacity float64
	IsSmall                  bool
	MinimumDuration          *int
	MaximumDuration          *int
	RecoveryDuration         *int
	RampRate                 *float64
	AccountingPointID        int
	GridNodeID               *string
	GridValidationStatus     string
	GridValidationNotes      *string
	ValidatedAt              pgtype.Timestamptz
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
	ReplacedBy               *int
	ReplacedAt               pgtype.Timestamptz
}

type ApiControllableUnitServiceProvider struct {
	ID                 int
	ControllableUnitID int
	ServiceProviderID  int
	EndUserID          int
	ContractReference  string
	ValidFrom          pgtype.Timestamptz
	ValidTo            pgtype.Timestamptz
	RecordedBy         int
	RecordedAt         pgtype.Timestamptz
}

type ApiControllableUnitServiceProviderHistory struct {
	ControllableUnitServiceProviderID int
	ID                                int
	ControllableUnitID                int
	ServiceProviderID                 int
	EndUserID                         int
	ContractReference                 string
	ValidFrom                         pgtype.Timestamptz
	ValidTo                           pgtype.Timestamptz
	RecordedBy                        int
	RecordedAt                        pgtype.Timestamptz
	ReplacedBy                        *int
	ReplacedAt                        pgtype.Timestamptz
}

type ApiControllableUnitSuspension struct {
	ID                       int
	ControllableUnitID       int
	ImpactedSystemOperatorID int
	Reason                   string
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
}

type ApiControllableUnitSuspensionComment struct {
	ID                           int
	ControllableUnitSuspensionID int
	CreatedBy                    int
	CreatedAt                    pgtype.Timestamptz
	Visibility                   string
	Content                      string
	RecordedBy                   int
	RecordedAt                   pgtype.Timestamptz
}

type ApiControllableUnitSuspensionCommentHistory struct {
	ControllableUnitSuspensionCommentID int
	ID                                  int
	ControllableUnitSuspensionID        int
	CreatedBy                           int
	CreatedAt                           pgtype.Timestamptz
	Visibility                          string
	Content                             string
	RecordedBy                          int
	RecordedAt                          pgtype.Timestamptz
	ReplacedBy                          *int
	ReplacedAt                          pgtype.Timestamptz
}

type ApiControllableUnitSuspensionHistory struct {
	ControllableUnitSuspensionID int
	ID                           int
	ControllableUnitID           int
	ImpactedSystemOperatorID     int
	Reason                       string
	RecordedBy                   int
	RecordedAt                   pgtype.Timestamptz
	ReplacedBy                   *int
	ReplacedAt                   pgtype.Timestamptz
}

type ApiEntity struct {
	ID             int
	BusinessID     string
	BusinessIDType string
	Name           string
	Type           string
	RecordedBy     int
	RecordedAt     pgtype.Timestamptz
}

type ApiEntityClient struct {
	ID           int
	EntityID     int
	Name         *string
	ClientID     string
	PartyID      int
	Scopes       []string
	ClientSecret *string
	PublicKey    *string
	RecordedBy   int
	RecordedAt   pgtype.Timestamptz
}

type ApiEvent struct {
	ID          int
	Specversion string
	Time        pgtype.Timestamptz
	Type        string
	Source      string
	Data        *string
}

type ApiIdentity struct {
	ID         int
	EntityID   int
	EntityName string
	PartyID    *int
	PartyName  *string
}

type ApiNotice struct {
	PartyID int
	Type    string
	Source  string
	Data    []byte
}

type ApiNotification struct {
	ID           int
	Acknowledged bool
	EventID      int
	PartyID      int
	RecordedBy   int
	RecordedAt   pgtype.Timestamptz
}

type ApiParty struct {
	ID             int
	BusinessID     string
	BusinessIDType string
	EntityID       int
	Name           string
	Role           string
	Type           string
	Status         string
	RecordedBy     int
	RecordedAt     pgtype.Timestamptz
}

type ApiPartyHistory struct {
	PartyID        int
	ID             int
	BusinessID     string
	BusinessIDType string
	EntityID       int
	Name           string
	Role           string
	Type           string
	Status         string
	RecordedBy     int
	RecordedAt     pgtype.Timestamptz
	ReplacedBy     *int
	ReplacedAt     pgtype.Timestamptz
}

type ApiPartyMembership struct {
	ID         int
	PartyID    int
	EntityID   int
	Scopes     []string
	RecordedBy int
	RecordedAt pgtype.Timestamptz
}

type ApiPartyMembershipHistory struct {
	PartyMembershipID int
	ID                int
	PartyID           int
	EntityID          int
	Scopes            []string
	RecordedBy        int
	RecordedAt        pgtype.Timestamptz
	ReplacedBy        *int
	ReplacedAt        pgtype.Timestamptz
}

type ApiProductType struct {
	ID         int
	BusinessID string
	Name       string
	Service    string
	Products   string
}

type ApiServiceProviderProductApplication struct {
	ID                int
	ServiceProviderID int
	SystemOperatorID  int
	ProductTypeIds    []int
	Status            string
	Notes             *string
	QualifiedAt       pgtype.Timestamptz
	RecordedBy        int
	RecordedAt        pgtype.Timestamptz
}

type ApiServiceProviderProductApplicationComment struct {
	ID                                  int
	ServiceProviderProductApplicationID int
	CreatedBy                           int
	CreatedAt                           pgtype.Timestamptz
	Visibility                          string
	Content                             string
	RecordedBy                          int
	RecordedAt                          pgtype.Timestamptz
}

type ApiServiceProviderProductApplicationCommentHistory struct {
	ServiceProviderProductApplicationCommentID int
	ID                                         int
	ServiceProviderProductApplicationID        int
	CreatedBy                                  int
	CreatedAt                                  pgtype.Timestamptz
	Visibility                                 string
	Content                                    string
	RecordedBy                                 int
	RecordedAt                                 pgtype.Timestamptz
	ReplacedBy                                 *int
	ReplacedAt                                 pgtype.Timestamptz
}

type ApiServiceProviderProductApplicationHistory struct {
	ServiceProviderProductApplicationID int
	ID                                  int
	ServiceProviderID                   int
	SystemOperatorID                    int
	ProductTypeIds                      []int
	Status                              string
	Notes                               *string
	QualifiedAt                         pgtype.Timestamptz
	RecordedBy                          int
	RecordedAt                          pgtype.Timestamptz
	ReplacedBy                          *int
	ReplacedAt                          pgtype.Timestamptz
}

type ApiServiceProviderProductSuspension struct {
	ID                        int
	ProcuringSystemOperatorID int
	ServiceProviderID         int
	ProductTypeIds            []int
	Reason                    string
	RecordedBy                int
	RecordedAt                pgtype.Timestamptz
}

type ApiServiceProviderProductSuspensionComment struct {
	ID                                 int
	ServiceProviderProductSuspensionID int
	CreatedBy                          int
	CreatedAt                          pgtype.Timestamptz
	Visibility                         string
	Content                            string
	RecordedBy                         int
	RecordedAt                         pgtype.Timestamptz
}

type ApiServiceProviderProductSuspensionCommentHistory struct {
	ServiceProviderProductSuspensionCommentID int
	ID                                        int
	ServiceProviderProductSuspensionID        int
	CreatedBy                                 int
	CreatedAt                                 pgtype.Timestamptz
	Visibility                                string
	Content                                   string
	RecordedBy                                int
	RecordedAt                                pgtype.Timestamptz
	ReplacedBy                                *int
	ReplacedAt                                pgtype.Timestamptz
}

type ApiServiceProviderProductSuspensionHistory struct {
	ServiceProviderProductSuspensionID int
	ID                                 int
	ProcuringSystemOperatorID          int
	ServiceProviderID                  int
	ProductTypeIds                     []int
	Reason                             string
	RecordedBy                         int
	RecordedAt                         pgtype.Timestamptz
	ReplacedBy                         *int
	ReplacedAt                         pgtype.Timestamptz
}

type ApiServiceProvidingGroup struct {
	ID                int
	Name              string
	ServiceProviderID int
	Status            string
	RecordedBy        int
	RecordedAt        pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridPrequalification struct {
	ID                       int
	ServiceProvidingGroupID  int
	ImpactedSystemOperatorID int
	Status                   string
	Notes                    *string
	PrequalifiedAt           pgtype.Timestamptz
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridPrequalificationComment struct {
	ID                                          int
	ServiceProvidingGroupGridPrequalificationID int
	CreatedBy                                   int
	CreatedAt                                   pgtype.Timestamptz
	Visibility                                  string
	Content                                     string
	RecordedBy                                  int
	RecordedAt                                  pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridPrequalificationCommentHistory struct {
	ServiceProvidingGroupGridPrequalificationCommentID int
	ID                                                 int
	ServiceProvidingGroupGridPrequalificationID        int
	CreatedBy                                          int
	CreatedAt                                          pgtype.Timestamptz
	Visibility                                         string
	Content                                            string
	RecordedBy                                         int
	RecordedAt                                         pgtype.Timestamptz
	ReplacedBy                                         *int
	ReplacedAt                                         pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridPrequalificationHistory struct {
	ServiceProvidingGroupGridPrequalificationID int
	ID                                          int
	ServiceProvidingGroupID                     int
	ImpactedSystemOperatorID                    int
	Status                                      string
	Notes                                       *string
	PrequalifiedAt                              pgtype.Timestamptz
	RecordedBy                                  int
	RecordedAt                                  pgtype.Timestamptz
	ReplacedBy                                  *int
	ReplacedAt                                  pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridSuspension struct {
	ID                       int
	ImpactedSystemOperatorID int
	ServiceProvidingGroupID  int
	Reason                   string
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridSuspensionComment struct {
	ID                                    int
	ServiceProvidingGroupGridSuspensionID int
	CreatedBy                             int
	CreatedAt                             pgtype.Timestamptz
	Visibility                            string
	Content                               string
	RecordedBy                            int
	RecordedAt                            pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridSuspensionCommentHistory struct {
	ServiceProvidingGroupGridSuspensionCommentID int
	ID                                           int
	ServiceProvidingGroupGridSuspensionID        int
	CreatedBy                                    int
	CreatedAt                                    pgtype.Timestamptz
	Visibility                                   string
	Content                                      string
	RecordedBy                                   int
	RecordedAt                                   pgtype.Timestamptz
	ReplacedBy                                   *int
	ReplacedAt                                   pgtype.Timestamptz
}

type ApiServiceProvidingGroupGridSuspensionHistory struct {
	ServiceProvidingGroupGridSuspensionID int
	ID                                    int
	ImpactedSystemOperatorID              int
	ServiceProvidingGroupID               int
	Reason                                string
	RecordedBy                            int
	RecordedAt                            pgtype.Timestamptz
	ReplacedBy                            *int
	ReplacedAt                            pgtype.Timestamptz
}

type ApiServiceProvidingGroupHistory struct {
	ServiceProvidingGroupID int
	ID                      int
	Name                    string
	ServiceProviderID       int
	Status                  string
	RecordedBy              int
	RecordedAt              pgtype.Timestamptz
	ReplacedBy              *int
	ReplacedAt              pgtype.Timestamptz
}

type ApiServiceProvidingGroupMembership struct {
	ID                      int
	ControllableUnitID      int
	ServiceProvidingGroupID int
	ValidFrom               pgtype.Timestamptz
	ValidTo                 pgtype.Timestamptz
	RecordedBy              int
	RecordedAt              pgtype.Timestamptz
}

type ApiServiceProvidingGroupMembershipHistory struct {
	ServiceProvidingGroupMembershipID int
	ID                                int
	ControllableUnitID                int
	ServiceProvidingGroupID           int
	ValidFrom                         pgtype.Timestamptz
	ValidTo                           pgtype.Timestamptz
	RecordedBy                        int
	RecordedAt                        pgtype.Timestamptz
	ReplacedBy                        *int
	ReplacedAt                        pgtype.Timestamptz
}

type ApiServiceProvidingGroupProductApplication struct {
	ID                        int
	ServiceProvidingGroupID   int
	ProcuringSystemOperatorID int
	ProductTypeIds            []int
	Status                    string
	Notes                     *string
	PrequalifiedAt            pgtype.Timestamptz
	VerifiedAt                pgtype.Timestamptz
	RecordedBy                int
	RecordedAt                pgtype.Timestamptz
}

type ApiServiceProvidingGroupProductApplicationHistory struct {
	ServiceProvidingGroupProductApplicationID int
	ID                                        int
	ServiceProvidingGroupID                   int
	ProcuringSystemOperatorID                 int
	ProductTypeIds                            []int
	Status                                    string
	Notes                                     *string
	PrequalifiedAt                            pgtype.Timestamptz
	VerifiedAt                                pgtype.Timestamptz
	RecordedBy                                int
	RecordedAt                                pgtype.Timestamptz
	ReplacedBy                                *int
	ReplacedAt                                pgtype.Timestamptz
}

type ApiServiceProvidingGroupProductSuspension struct {
	ID                        int
	ProcuringSystemOperatorID int
	ServiceProvidingGroupID   int
	ProductTypeIds            []int
	Reason                    string
	RecordedBy                int
	RecordedAt                pgtype.Timestamptz
}

type ApiServiceProvidingGroupProductSuspensionComment struct {
	ID                                       int
	ServiceProvidingGroupProductSuspensionID int
	CreatedBy                                int
	CreatedAt                                pgtype.Timestamptz
	Visibility                               string
	Content                                  string
	RecordedBy                               int
	RecordedAt                               pgtype.Timestamptz
}

type ApiServiceProvidingGroupProductSuspensionCommentHistory struct {
	ServiceProvidingGroupProductSuspensionCommentID int
	ID                                              int
	ServiceProvidingGroupProductSuspensionID        int
	CreatedBy                                       int
	CreatedAt                                       pgtype.Timestamptz
	Visibility                                      string
	Content                                         string
	RecordedBy                                      int
	RecordedAt                                      pgtype.Timestamptz
	ReplacedBy                                      *int
	ReplacedAt                                      pgtype.Timestamptz
}

type ApiServiceProvidingGroupProductSuspensionHistory struct {
	ServiceProvidingGroupProductSuspensionID int
	ID                                       int
	ProcuringSystemOperatorID                int
	ServiceProvidingGroupID                  int
	ProductTypeIds                           []int
	Reason                                   string
	RecordedBy                               int
	RecordedAt                               pgtype.Timestamptz
	ReplacedBy                               *int
	ReplacedAt                               pgtype.Timestamptz
}

type ApiSystemOperatorProductType struct {
	ID               int
	SystemOperatorID int
	ProductTypeID    int
	Status           string
	RecordedBy       int
	RecordedAt       pgtype.Timestamptz
}

type ApiSystemOperatorProductTypeHistory struct {
	SystemOperatorProductTypeID int
	ID                          int
	SystemOperatorID            int
	ProductTypeID               int
	Status                      string
	RecordedBy                  int
	RecordedAt                  pgtype.Timestamptz
	ReplacedBy                  *int
	ReplacedAt                  pgtype.Timestamptz
}

type ApiTechnicalResource struct {
	ID                 int
	Name               string
	ControllableUnitID int
	Details            *string
	RecordedBy         int
	RecordedAt         pgtype.Timestamptz
}

type ApiTechnicalResourceHistory struct {
	TechnicalResourceID int
	ID                  int
	Name                string
	ControllableUnitID  int
	Details             *string
	RecordedBy          int
	RecordedAt          pgtype.Timestamptz
	ReplacedBy          *int
	ReplacedAt          pgtype.Timestamptz
}

type NotificationControllableUnitEndUser struct {
	ControllableUnitID int
	EndUserID          int
	ValidTimeRange     pgtype.Range[pgtype.Timestamptz]
}

type NotificationControllableUnitSystemOperator struct {
	ControllableUnitID int
	SystemOperatorID   int
	ValidTimeRange     pgtype.Range[pgtype.Timestamptz]
}
