---
# Base template for OpenAPI document

openapi: 3.1.0
info:
  title: Flexibility Information System Main API
  description: Norwegian Flexibility Information System Main API
  contact:
    name: Elhub AS
    url: https://elhub.no
    email: post@elhub.no
  version: 0.0.1
externalDocs:
  description: TODO
  url: https://todo.example.com
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
tags:
  # TODO externaldocs
  - name: introspection
    description: Introspection
  - name: controllable_unit
    description: Controllable unit
components:
  parameters: {}
  schemas:
    error_message:
      description: Error message returned from the API.
      type: object
      properties:
        code:
          type: string
          pattern: '^[A-Z0-9]+$'
          description: The error code.
          example: PT418
        details:
          type: [string, 'null']
          description: Detailed information about the error.
          example: null
        hint:
          type: [string, 'null']
          description: A hint to help resolve the error.
          example: null
        message:
          type: string
          description: The error message.
          example: error
      required:
        - code
        - message
    controllable_unit_lookup_request:
      summary: Controllable unit lookup
      description: Request schema for controllable unit lookup operations
      type: object
      properties:
        end_user:
          description: Birth number or organisation number of the end user.
          format: text
          type: string
          example: '8d4bde5a-decc-4e92-9a04-a64f258921f0'
        controllable_unit:
          description: The business ID of the controllable unit to lookup.
          format: text
          type: string
          # yamllint disable-line rule:line-length
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: '53919b79-876f-4dad-8bde-b29368367604'
        accounting_point:
          description: >-
            The accounting point ID of the controllable unit(s) to lookup.
            `GSRN` metering point id.
          format: text
          type: string
          pattern: '^[1-9][0-9]{17}$'
          example: '709000000000000057'
      required:
        - end_user
    controllable_unit_lookup_response:
      summary: Controllable unit lookup
      description: Response schema for controllable unit lookup operations
      type: array
      items:
        type: object
        properties:
          id:
            description: The surrogate key of the controllable unit.
            format: bigint
            type: integer
            example: 11
          business_id:
            description: The business ID of the controllable unit.
            format: text
            type: string
            example: '53919b79-876f-4dad-8bde-b29368367604'
          name:
            description: The name of the controllable unit.
            format: text
            type: string
            example: 'Car Charger #54'
          accounting_point_id:
            description: The accounting point ID of the controllable unit.
            format: text
            type: string
            pattern: '^[1-9][0-9]{17}$'
            example: '709000000000000057'
          end_user_id:
            description: >-
              The ID of the current end user on the controllable unit.
            format: bigint
            type: integer
            example: 379
          technical_resources:
            description: >-
              The technical resources belonging to the controllable unit.
            type: array
            items:
              type: object
              properties:
                id:
                  description: The surrogate key of the technical resource.
                  format: bigint
                  type: integer
                  example: 17
                name:
                  description: The name of the technical resource.
                  format: text
                  type: string
                  example: 'Battery Unit A'
                details:
                  description: >-
                    Additional details about the technical resource.
                  format: text
                  type: string
                  example: '16A'
              required:
                - id
                - name
        required:
          - id
          - business_id
          - name
          - accounting_point_id
          - end_user_id
          - technical_resources
paths:
  /openapi.json:
    get:
      operationId: read_openapi_json
      summary: Read OpenAPI JSON Document
      description: >-
        Introspection for the Flexibility Information System main API.
        The document is following the OpenAPI 3.1 spec.
      tags:
        - introspection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
  /controllable_unit/lookup:
    post:
      operationId: call_controllable_unit_lookup
      summary: Call - Controllable unit lookup
      description: >-
        Lookup a controllable unit from end user ID and business and/or
        accounting point ID.
      tags:
        - controllable_unit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/controllable_unit_lookup_request'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/controllable_unit_lookup_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
          description: Internal Server Error
servers:
  - url: https://flex-test.elhub.no/api/v0
    description: External test environment
  - url: https://test.flex.internal:6443/api/v0
    description: Local development
