// code generated by openapi_to_embed_relations.py -- DO NOT EDIT

package data

var embedRelations = map[string]map[string]string{
	"accounting_point": {
		"balance_responsible_party": "accounting_point_balance_responsible_party",
		"bidding_zone": "accounting_point_bidding_zone",
		"controllable_unit": "controllable_unit",
		"end_user": "accounting_point_end_user",
		"energy_supplier": "accounting_point_energy_supplier",
		"grid_location": "accounting_point_grid_location",
		"metering_grid_area": "accounting_point_metering_grid_area",
		"system_operator": "party",
	},
	"accounting_point_balance_responsible_party": {
		"accounting_point": "accounting_point",
		"balance_responsible_party": "party",
	},
	"accounting_point_bidding_zone": {
		"accounting_point": "accounting_point",
	},
	"accounting_point_end_user": {
		"accounting_point": "accounting_point",
		"end_user": "party",
	},
	"accounting_point_energy_supplier": {
		"accounting_point": "accounting_point",
		"energy_supplier": "party",
	},
	"accounting_point_grid_location": {
		"accounting_point": "accounting_point",
	},
	"accounting_point_metering_grid_area": {
		"accounting_point": "accounting_point",
		"metering_grid_area": "metering_grid_area",
	},
	"controllable_unit": {
		"accounting_point": "accounting_point",
		"service_provider": "controllable_unit_service_provider",
		"service_providing_group_membership": "service_providing_group_membership",
		"summary": "controllable_unit_summary",
		"suspension": "controllable_unit_suspension",
		"technical_resource": "technical_resource",
	},
	"controllable_unit_service_provider": {
		"controllable_unit": "controllable_unit",
		"end_user": "party",
		"service_provider": "party",
	},
	"controllable_unit_summary": {
		"controllable_unit": "controllable_unit",
	},
	"controllable_unit_suspension": {
		"controllable_unit": "controllable_unit",
		"impacted_system_operator": "party",
	},
	"entity": {
		"client": "entity_client",
		"identity": "identity",
		"party": "party",
		"party_membership": "party_membership",
	},
	"entity_client": {
		"entity": "entity",
		"party": "party",
	},
	"event": {
		"notification": "notification",
	},
	"identity": {
		"entity": "entity",
		"party": "party",
	},
	"metering_grid_area": {
		"accounting_point_metering_grid_area": "accounting_point_metering_grid_area",
	},
	"notice": {
		"party": "party",
	},
	"notification": {
		"event": "event",
		"party": "party",
	},
	"party": {
		"entity": "entity",
	},
	"party_membership": {
		"entity": "entity",
		"party": "party",
	},
	"product_type": {
		"system_operator_product_type": "system_operator_product_type",
	},
	"service_provider_product_application": {
		"service_provider": "party",
		"system_operator": "party",
	},
	"service_provider_product_suspension": {
		"procuring_system_operator": "party",
		"service_provider": "party",
	},
	"service_providing_group": {
		"grid_prequalification": "service_providing_group_grid_prequalification",
		"grid_suspension": "service_providing_group_grid_suspension",
		"membership": "service_providing_group_membership",
		"power_per_substation": "service_providing_group_power_per_substation",
		"product_application": "service_providing_group_product_application",
		"product_suspension": "service_providing_group_product_suspension",
		"service_provider": "party",
		"summary": "service_providing_group_summary",
	},
	"service_providing_group_grid_prequalification": {
		"impacted_system_operator": "party",
		"service_providing_group": "service_providing_group",
	},
	"service_providing_group_grid_suspension": {
		"impacted_system_operator": "party",
		"service_providing_group": "service_providing_group",
	},
	"service_providing_group_membership": {
		"controllable_unit": "controllable_unit",
		"service_providing_group": "service_providing_group",
	},
	"service_providing_group_power_per_substation": {
		"service_providing_group": "service_providing_group",
	},
	"service_providing_group_product_application": {
		"procuring_system_operator": "party",
		"service_providing_group": "service_providing_group",
	},
	"service_providing_group_product_suspension": {
		"procuring_system_operator": "party",
		"service_providing_group": "service_providing_group",
	},
	"service_providing_group_summary": {
		"service_providing_group": "service_providing_group",
	},
	"system_operator_product_type": {
		"product_type": "product_type",
		"system_operator": "party",
	},
	"technical_resource": {
		"controllable_unit": "controllable_unit",
	},
}
