@startuml controllable_unit_lookup
!theme plain

title Controllable Unit (CU) Registration

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "End User (EU)" AS EU
actor "Service Provider (SP)" as SP
participant "Flexibility Information System (FIS)" as FIS

EU <-> SP: Contractual agreement
activate SP

== Controllable Unit (CU) Lookup ==

SP -> FIS: Lookup existing CU on accounting point
note left
    Data required:
    - metering point id (MPID)
    - end user id
end note

activate FIS


@enduml
