@startuml controllable_unit_suspension

!theme plain

title Controllable Unit Suspension

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "Service Provider (SP)" as SP
participant "Flexibility\nInformation System (FIS)" as FIS
actor "System Operator (SO)" as SO 

== Suspension of controllable unit validation ==

activate SO
SO -> FIS: Create CU suspension

note right
    Data:
        - name of CU
        - reason for suspension
end note

activate FIS

FIS --> SO: Ok
deactivate SO
FIS-->SP: Notify
activate SP 
loop All ISOs for which the CU is validated
    |||
    FIS --> SO: Notify
    deactivate FIS
    |||
end

SP --> FIS: Get suspension
activate FIS 
FIS --> SP: Data incl. reason for suspension
deactivate FIS

note over SP
    SP notifies end users
    of the suspension when
    neccessary.
end note

== Handle suspension ==
|||
note over FIS
    SP and SO must probably communicate to sort out the issues that caused the 
    suspension. This can be done using comments on the CU suspension in the FIS
    or other communication mediums like email and phone. 
end note
|||
deactivate SP

== Reinstatement of controllable unit ==

SO --> FIS: Delete CU suspension
activate SO 
|||
activate FIS
FIS --> SO: Ok
deactivate SO
FIS --> SP: Notify

loop All ISOs for which the CU is validated
    |||
    FIS --> SO: Notify
    deactivate FIS
    |||
end

@enduml