@startuml controllable_unit_registration
!theme plain

title Controllable Unit (CU) Registration

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "End User (EU)" AS EU
actor "Service Provider (SP)" as SP
participant "Flexibility Information System (FIS)" as FIS
actor "System Operator (SO)" as SO

EU <-> SP: Contractual agreement
activate SP

== Register Controllable Unit (CU) ==

SP -> FIS: Register new CU
note left
    Minimum data required:
    - name
    - metering point id (MPID)
end note

activate FIS
FIS -> FIS: Assign unique ID
FIS -> FIS: Set status to [new]
FIS --> SP: Return w/ unique ID
FIS --> EU : Notify new CU
note right
    FIS knows who the end user is
    based on metering point ID and
    data from Elhub.
end note
FIS --> SO: Notify new CU to\nConnecting System Operator
deactivate FIS

activate SO
SO -> SO: Map MPID to\ngrid node
SO -> FIS: Update CU with grid node
deactivate SO
activate FIS
FIS --> SP: Notify CU updated
deactivate FIS

== Register Controllable Unit Service Provider Contract ==

SP -> FIS: Register CU service provider contract
activate FIS
FIS --> SP: OK
FIS --> EU : Notify CU SP contract
FIS --> SO: Notify CU SP contract to\nConnecting System Operator
deactivate FIS

SP -> FIS: Get (possibly) updated CU data
activate FIS
FIS --> SP: Return CU data
deactivate FIS

== Register Controllable Unit Data ==

SP -> FIS: Update CU data
note left
    SP must ensure that the CU
    data is up to date:
    - name
    - regulation direction
    - durations
    - etc.
end note
activate FIS
FIS --> SP: OK
deactivate FIS

== Technical Resource (TR) registration ==

'There is no reference to technical resource in the ACER document
'but ref to existing definitions ‘demand unit’ means an indivisible set of installations containing equipment which can be actively controlled by a demand facility
'owner or by a CDSO, either individually or commonly as part of demand agregation through a third party to provide demand response services
'to relevant system operators and relevant TSOs  or is a V1G electric vehicle and associated V1G electric vehicle supply equipment,
'power-to-gas demand unit or heat-pump.

loop For each relevant TR of the CU

loop Relevant technical resources
    |||
    SP -> FIS: Add Technical Resource
    note left
        Data:
        - name
        - technical information
    end note
    activate FIS
    FIS --> SP: OK
    deactivate FIS
    |||
end

== Controllable Unit Grid Validation ==

SP -> FIS: Update status to [active]
deactivate SP
activate FIS
note right
    Setting the status to active
    indicates that the CU's data is
    ready for validation by SO.
end note
FIS --> SP: OK

loop All Impacted System Operators
    |||
    FIS --> SO: Notify update to ISO
    note left
        ISOs are notified, but does <b>not</b>
        take part in grid validations.

        ISOs are SOs whose observability area includes
        the grid node where the CU is connected.
    end note
    |||
end

FIS --> SO: Notify update to CSO
deactivate FIS
activate SO

note over SO
    CSO initiates grid validation
    without undue delay.
    The validation status is set to
    pending by FIS
end note
loop When status changes
    SO -> FIS: Update FIS with status
    note left
        Relevant statuses:

        - pending
        - in progress
        - incomplete_information
        - validated
        - validation_failed

        The CSO should add notes and update
        last validated time when relevant.
    end note
    activate FIS
    FIS --> SO: OK
    FIS --> SP: Notify SP grid validation status updated
    deactivate FIS
    |||
end


@enduml
