@startuml delivery-verification

!theme plain

title Delivery verification

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "Service Provider (SP)" as SP
participant "Market platform" as MP
participant "Flexibility\nInformation System (FIS)" as FIS
participant "Time series\nservices" as TS
actor "Procuring System Operator (PSO)" as PSO 
participant "Elhub" as EL
actor "Connecting System Operator (CSO)" as CSO 

== Bid activation ==

activate SP
SP -> MP: Send bid
SP -> TS: Send baseline

Activate PSO
PSO -> TS: Get baseline
TS --> PSO: Baseline

PSO -> MP: Accept bid
MP --> PSO: Bid volume

note over SP
    SP activates the SPGs resources
    after the bid is activated
end note

SP -> TS: Measured and metering values
deactivate SP

PSO -> MP: Get bid activation information
MP --> PSO: Bid activation information

activate CSO
CSO -> EL: Metering values
deactivate CSO

note over PSO
    PSO uses the bid activation information to collect
    the right time series for the delivery verification.
end note

== Delivery verification ==

PSO -> FIS: Get CU/SPG/MP ID
FIS --> PSO: CU/SPG/MP ID

note over PSO
    PSO uses FIS to get the IDs of the CUs/SPG and MPID
    in order to collect the right metering values.
end note

PSO -> TS: Get measured values, metering values and baseline
TS --> PSO: Measured values, metering values and baseline
PSO -> EL: Get metering values
EL --> PSO: Metering values

note over PSO
    PSO uses the collected time series and the
    activated bid to do the delivery verification
    analysis.
end note

PSO -> FIS: Register result of delivery verification
FIS --> SP: Notify

deactivate PSO
