@startuml login_sequence
!theme plain

title Login Sequence

skinparam LifelineStrategy solid
skinparam SequenceMessageAlign direction

participant "Entity Client" as client
participant "FIS" as fis

== JWT Bearer grant step ==

client -> fis: ""POST /auth/v1/token""\n\
""grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer""\n\
""assertion=<signed JWT>""
activate fis #d6e4d5
activate client #d6e4d5
rnote right of client
The assertion is signed with the entity client's private key.
end note

fis -> client: ""200 OK""
deactivate fis
rnote left of fis
  Entity access token : ""<color #05677d>x6E9g.bGEqW0.u4teR</color>""
end note

|||

== Collecting information ==

client -> fis:\
""GET /auth/v1/userinfo""\n\
""Authorization: Bearer <color #05677d>x6E9g.bGEqW0.u4teR</color>""
activate fis #d6e4d5

fis -> client: ""200 OK""
deactivate fis
rnote left of fis
  This token corresponds to entity ""<color #05677d>12</color>"".
end note

|||

client -> fis:\
""GET /api/v1/party_membership?entity_id=<color #05677d>12</color>""\n\
""Authorization: Bearer <color #05677d>x6E9g.bGEqW0.u4teR</color>""
activate fis #d6e4d5

fis -> client: ""200 OK""
deactivate fis
rnote left of fis
  Entity ""<color #05677d>12</color>"" can assume parties ""<color #886599>3</color>"" and ""<color #886599>9</color>"".
end note

|||

== Token Exchange step ==

client -> fis:\
""POST /auth/v1/token""\n\
""grant_type=urn:ietf:params:oauth:grant-type:token-exchange""\n\
""actor_token=<entity access token>""\n\
""actor_token_type=urn:ietf:params:oauth:token-type:jwt""\n\
""scope=assume:party:<color #886599>9</color>""
activate fis #d6e4d5
rnote right of client
As entity <color #05677d>12</color>, \
I want to assume party ""<color #886599>9</color>"".
end note

fis -> client: ""200 OK""
deactivate fis
rnote left of fis
  Access token : ""<color #886599>7pMlw.aFdZ8b.kJkg5</color>""
end note

@enduml
