@startuml org_access_control_management

!theme plain

title Service Provider (SP) Registration

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "Ola" as Ola
actor "Kari" as Kari
actor "FIS Operator" as FISO
participant "Flexibility\nInformation System (FIS)" as FIS

== Bootstrap: Kari & FISO ==

note over FIS
Entities and parties for Solkraft AS in the system:
- Entity: Solkraft AS
- Party: Solkraft AS (Organisation)
- Party: Solkraft AS (Energy Supplier)
- Party: Solkraft AS (Service Provider)
end note
Kari -> FISO: Give person number
note left of FISO
040782 54321
end note
FISO -> FIS: Create entity for Kari
activate FIS
return OK
FISO -> FIS: Add Kari to Solkraft AS (Organisation)
activate FIS
note left of FIS
Admin scopes:
- manage:auth
- read:data
- use:data:entity:lookup
- manage:data:party_membership
- manage:data:entity_client
end note
return OK

== Administration: Kari ==

Ola -> Kari: Give person number
note left of Kari
010170 12345
end note

Kari -> FIS: Login as Kari then assume Solkraft AS (Organisation)
activate FIS
return OK
activate Kari
Kari -> FIS: Entity lookup for Ola's person number
activate FIS
return Entity ID for Ola
Kari -> FIS: Add Ola to Solkraft AS (Energy Supplier)
note left of FIS
Regular scopes:
- manage:auth
- manage:data
end note
activate FIS
return OK
deactivate Kari

== Energy Supplier operations: Ola ==

Ola -> FIS: Login as Ola then assume Solkraft AS (Energy Supplier)
activate FIS
return OK
activate Ola
Ola -> FIS: Perform operations in the system as Solkraft AS (Energy Supplier)
activate FIS
return OK
deactivate Ola

@enduml
