@startuml revocation
!theme plain

title Service Provider Contract Revocation and Termination 

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "End User (EU)" AS EU
actor "Service Provider (SP)" as SP
participant "Flexibility Information System (FIS)" as FIS

== Revocation and Termination ==

SP -> FIS: Register end date
activate SP
note left SP
Data:
- Service provider
- Controllable unit
- End date

Contract end date must be 
2-4 weeks in the future
end note
activate FIS
FIS -> FIS: End existing contract 
FIS --> SP: OK
deactivate SP
FIS --> EU: Notify
deactivate FIS

|||
@enduml
