@startuml service_providing_group_registration
!theme plain

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

title Service Providing Group (SPG) Registration

actor "Service Provider (SP)" as SP
participant "Flexibility Information System (FIS)" as FIS


== Service Providing Group (SPG) Registration ==
activate SP

SP -> FIS: Register new SPG
deactivate SP

note left
    Data:
    - name
    - bidding zone
end note

activate FIS
FIS -> FIS: Assign unique ID
FIS -> FIS: Set status to [new]
FIS --> SP: Return SPG w/unique ID
deactivate FIS
activate SP

== Add Controllable Units (CU) to Service Providing Group (SPG) ==

SP -> FIS: Choose CU's from list of CU's
activate FIS
FIS --> SP: Return chosen CU's
deactivate FIS

== Activate Service Providing Group ==

SP -> FIS: Update\nstatus to [active]
note right
    Setting the status to active
    indicates that the SP has added all
    CUs and the SPG is ready to be used
    in a product application.
end note
activate FIS
FIS --> SP: OK
deactivate SP

@enduml
