@startdot service_providing_group_prequalification_status
digraph G {
    layout=dot;
    overlap=false;

    node [shape=rect,width=0.1,height=0.1,margin=0.04];

    start [shape=point];

    // status - Atricle 30.3.b
    requested;
    in_progress;
    conditionally_approved;
    approved;
    not_approved;

    // transitions
    start -> requested [label="", color="pink"];
    requested -> in_progress [label="", color="green"];
    approved -> requested [label="SP significantly \nupdates data", color="green"];
    in_progress -> conditionally_approved [label="", color="green"];
    conditionally_approved -> requested [label="SP updates \ndata", color="green"];
    in_progress -> approved [label="", color="green"];
    in_progress -> not_approved [label="", color="green"];
    not_approved -> requested [label="SP updates \ndata", color="green"];

   }
@enddot
