@startuml service_provider_switching
!theme plain

title Service provider switching

autonumber
skinparam note {
    BackgroundColor #FFFFBD
}

actor "End User (EU)" AS EU
actor "New Service Provider (SP_NEW)" as SP_NEW
actor "Old Service Provider (SP_OLD)" as SP_OLD
participant "Flexibility Information System (FIS)" as FIS
actor "System Operator (SO)" as SO

== Initiate Switching ==


EU <-> SP_NEW: Contractual agreement
Note right SP_NEW
    The end user contacts a new service provider in order 
    to obtain a new contract for controllable unit services 
    and ending of the contract with the present service provider
end note
== Verification of controllable unit ==

Note left SP_NEW
    The new servive provider will verify the
    controllable unit by using contrallable unit business id
end note

SP_NEW -> FIS: Verification of controllable unit
FIS --> SP_NEW: Return with controllable unit data or a negitive response

== Switching ==

Note left SP_NEW
    Data: service provider business id,
          controllable unit business id,
          contract reference and contract start date
end note
SP_NEW -> FIS: Request switch of controllable unit 
Note right FIS
    The new service provider requests to be 
    registered in FIS as the new service provider
    for the controllable unit  
end note

FIS -> FIS: Future contract updates
FIS --> SP_NEW: Return switch of service provider request results
Note right FIS
    FIS notifies all affected parties directly
    after positive validation of the switch
    of service provider request and contract start date
end note

FIS --> SO: Notify with controllable unit business id \nand new service providers contract start date
FIS --> SP_OLD: Notify with controllable unit business id \nand new service providers contract start date


== Post Switching ==
Note right SP_NEW
    New service provider will use dedicated process
    updating controllable unit characterisitcs and assigning
    new controllable unit to service providing group(s)
end note

@enduml
