// code generated by openapi_to_embed_relations.py -- DO NOT EDIT

package grid

var embedRelations = map[string]map[string]string{
	"line": {
		"from_substation_cluster": "substation_cluster",
		"to_substation_cluster": "substation_cluster",
	},
	"substation": {
		"substation_cluster": "substation_cluster",
	},
	"substation_cluster": {
		"line": "line",
		"substation": "substation",
	},
}
