ktor:
  application:
    modules:
      - no.elhub.flex.ApplicationKt.module
  deployment:
    port: 8080
  database:
    url: ${FLEX_DATABASE_URL}
    username: ${FLEX_DATABASE_USERNAME}
    password: ${FLEX_DATABASE_PASSWORD}
    driverClass: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10

flex:
  jwt-secret: ${FLEX_JWT_SECRET}

accounting-point-adapter:
  base-url: ${ACCOUNTING_POINT_ADAPTER_BASE_URL}
