ktor:
  application:
    modules:
      - no.elhub.flex.ApplicationKt.module
  deployment:
    port: 8080
  database:
    url: ${FLEX_DATABASE_URL}
    username: ${FLEX_DATABASE_USERNAME}
    password: ${FLEX_DATABASE_PASSWORD}
    driverClass: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10

flex:
  jwt-secret: ${FLEX_JWT_SECRET}
  timezone: ${FLEX_TIMEZONE:Europe/Oslo}

accounting-point-adapter:
  base-url: ${ACCOUNTING_POINT_ADAPTER_BASE_URL}
  api-key: ${ACCOUNTING_POINT_ADAPTER_API_KEY}
  sync-enabled: ${ACCOUNTING_POINT_ADAPTER_SYNC_ENABLED:true}

attachment-storage:
  bucket: ${S3_BUCKET}
  internal-endpoint: ${S3_INTERNAL_ENDPOINT}
  public-endpoint: ${S3_PUBLIC_ENDPOINT}
  region: ${S3_REGION}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
