// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package models

import (
	"context"
)

const entityLookup = `-- name: EntityLookup :one
SELECT
    entity_id::bigint,
    entity_found::boolean
FROM api.entity_lookup(
  $1::text,
  $2::text,
  $3::text
)
`

type EntityLookupRow struct {
	EntityID    int
	EntityFound bool
}

func (q *Queries) EntityLookup(ctx context.Context, entityBusinessID string, entityName string, entityType string) (EntityLookupRow, error) {
	row := q.db.QueryRow(ctx, entityLookup, entityBusinessID, entityName, entityType)
	var i EntityLookupRow
	err := row.Scan(&i.EntityID, &i.EntityFound)
	return i, err
}
