// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountingPoint struct {
	ID               int
	BusinessID       string
	SystemOperatorID int
	RecordedBy       int
	RecordedAt       pgtype.Timestamptz
}

type AccountingPointBalanceResponsibleParty struct {
	AccountingPointID         int
	BalanceResponsiblePartyID int
	EnergyDirection           string
	ValidFrom                 pgtype.Timestamptz
	ValidTo                   pgtype.Timestamptz
}

type ControllableUnit struct {
	ID                       int
	BusinessID               string
	Name                     string
	StartDate                pgtype.Date
	Status                   string
	RegulationDirection      string
	MaximumAvailableCapacity float64
	IsSmall                  bool
	MinimumDuration          *int
	MaximumDuration          *int
	RecoveryDuration         *int
	RampRate                 *float64
	AccountingPointID        int
	GridNodeID               *string
	GridValidationStatus     string
	GridValidationNotes      *string
	LastValidated            pgtype.Timestamptz
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
}

type ControllableUnitHistory struct {
	ControllableUnitID       int
	ID                       int
	BusinessID               string
	Name                     string
	StartDate                pgtype.Date
	Status                   string
	RegulationDirection      string
	MaximumAvailableCapacity float64
	IsSmall                  bool
	MinimumDuration          *int
	MaximumDuration          *int
	RecoveryDuration         *int
	RampRate                 *float64
	AccountingPointID        int
	GridNodeID               *string
	GridValidationStatus     string
	GridValidationNotes      *string
	LastValidated            pgtype.Timestamptz
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
	ReplacedBy               *int
	ReplacedAt               pgtype.Timestamptz
}

type ControllableUnitServiceProvider struct {
	ID                 int
	ControllableUnitID int
	ServiceProviderID  int
	EndUserID          int
	ContractReference  string
	ValidFrom          pgtype.Timestamptz
	ValidTo            pgtype.Timestamptz
	RecordedBy         int
	RecordedAt         pgtype.Timestamptz
}

type ControllableUnitServiceProviderHistory struct {
	ControllableUnitServiceProviderID int
	ID                                int
	ControllableUnitID                int
	ServiceProviderID                 int
	EndUserID                         int
	ContractReference                 string
	ValidFrom                         pgtype.Timestamptz
	ValidTo                           pgtype.Timestamptz
	RecordedBy                        int
	RecordedAt                        pgtype.Timestamptz
	ReplacedBy                        *int
	ReplacedAt                        pgtype.Timestamptz
}

type Entity struct {
	ID             int
	BusinessID     string
	BusinessIDType string
	Name           string
	Type           string
}

type EntityClient struct {
	ID           int
	EntityID     int
	Name         *string
	ClientID     string
	ClientSecret *string
	PublicKey    *string
	RecordedBy   int
	RecordedAt   pgtype.Timestamptz
}

type Event struct {
	ID          int
	Specversion string
	Time        pgtype.Timestamptz
	Type        string
	Source      string
	Data        *string
}

type Identity struct {
	ID         int
	EntityID   int
	EntityName string
	PartyID    *int
	PartyName  *string
}

type Notice struct {
	PartyID int
	Type    string
	Source  string
	Data    *string
}

type Notification struct {
	ID           int
	Acknowledged bool
	EventID      int
	PartyID      int
	RecordedBy   int
	RecordedAt   pgtype.Timestamptz
}

type Party struct {
	ID             int
	BusinessID     string
	BusinessIDType string
	EntityID       int
	Name           string
	Role           string
	Type           string
	Status         string
	RecordedBy     int
	RecordedAt     pgtype.Timestamptz
}

type PartyHistory struct {
	PartyID        int
	ID             int
	BusinessID     string
	BusinessIDType string
	EntityID       int
	Name           string
	Role           string
	Type           string
	Status         string
	RecordedBy     int
	RecordedAt     pgtype.Timestamptz
	ReplacedBy     *int
	ReplacedAt     pgtype.Timestamptz
}

type PartyMembership struct {
	ID         int
	PartyID    int
	EntityID   int
	RecordedBy int
	RecordedAt pgtype.Timestamptz
}

type PartyMembershipHistory struct {
	PartyMembershipID int
	ID                int
	PartyID           int
	EntityID          int
	RecordedBy        int
	RecordedAt        pgtype.Timestamptz
	ReplacedBy        *int
	ReplacedAt        pgtype.Timestamptz
}

type ProductType struct {
	ID         int
	BusinessID string
	Name       string
	Service    string
	Products   string
}

type ServiceProviderProductApplication struct {
	ID                int
	ServiceProviderID int
	SystemOperatorID  int
	ProductTypeIds    []int
	Status            string
	Notes             *string
	LastQualified     pgtype.Timestamptz
	RecordedBy        int
	RecordedAt        pgtype.Timestamptz
}

type ServiceProviderProductApplicationComment struct {
	ID                                  int
	ServiceProviderProductApplicationID int
	CreatedBy                           int
	CreatedAt                           pgtype.Timestamptz
	Visibility                          string
	Content                             string
	RecordedBy                          int
	RecordedAt                          pgtype.Timestamptz
}

type ServiceProviderProductApplicationCommentHistory struct {
	ServiceProviderProductApplicationCommentID int
	ID                                         int
	ServiceProviderProductApplicationID        int
	CreatedBy                                  int
	CreatedAt                                  pgtype.Timestamptz
	Visibility                                 string
	Content                                    string
	RecordedBy                                 int
	RecordedAt                                 pgtype.Timestamptz
	ReplacedBy                                 *int
	ReplacedAt                                 pgtype.Timestamptz
}

type ServiceProviderProductApplicationHistory struct {
	ServiceProviderProductApplicationID int
	ID                                  int
	ServiceProviderID                   int
	SystemOperatorID                    int
	ProductTypeIds                      []int
	Status                              string
	Notes                               *string
	LastQualified                       pgtype.Timestamptz
	RecordedBy                          int
	RecordedAt                          pgtype.Timestamptz
	ReplacedBy                          *int
	ReplacedAt                          pgtype.Timestamptz
}

type ServiceProvidingGroup struct {
	ID                int
	Name              string
	ServiceProviderID int
	Status            string
	RecordedBy        int
	RecordedAt        pgtype.Timestamptz
}

type ServiceProvidingGroupGridPrequalification struct {
	ID                       int
	ServiceProvidingGroupID  int
	ImpactedSystemOperatorID int
	Status                   string
	Notes                    *string
	LastPrequalified         pgtype.Timestamptz
	RecordedBy               int
	RecordedAt               pgtype.Timestamptz
}

type ServiceProvidingGroupGridPrequalificationHistory struct {
	ServiceProvidingGroupGridPrequalificationID int
	ID                                          int
	ServiceProvidingGroupID                     int
	ImpactedSystemOperatorID                    int
	Status                                      string
	Notes                                       *string
	LastPrequalified                            pgtype.Timestamptz
	RecordedBy                                  int
	RecordedAt                                  pgtype.Timestamptz
	ReplacedBy                                  *int
	ReplacedAt                                  pgtype.Timestamptz
}

type ServiceProvidingGroupHistory struct {
	ServiceProvidingGroupID int
	ID                      int
	Name                    string
	ServiceProviderID       int
	Status                  string
	RecordedBy              int
	RecordedAt              pgtype.Timestamptz
	ReplacedBy              *int
	ReplacedAt              pgtype.Timestamptz
}

type ServiceProvidingGroupMembership struct {
	ID                      int
	ControllableUnitID      int
	ServiceProvidingGroupID int
	ValidFrom               pgtype.Timestamptz
	ValidTo                 pgtype.Timestamptz
	RecordedBy              int
	RecordedAt              pgtype.Timestamptz
}

type ServiceProvidingGroupMembershipHistory struct {
	ServiceProvidingGroupMembershipID int
	ID                                int
	ControllableUnitID                int
	ServiceProvidingGroupID           int
	ValidFrom                         pgtype.Timestamptz
	ValidTo                           pgtype.Timestamptz
	RecordedBy                        int
	RecordedAt                        pgtype.Timestamptz
	ReplacedBy                        *int
	ReplacedAt                        pgtype.Timestamptz
}

type ServiceProvidingGroupProductApplication struct {
	ID                        int
	ServiceProvidingGroupID   int
	ProcuringSystemOperatorID int
	ProductTypeID             int
	Status                    string
	Notes                     *string
	LastPrequalified          pgtype.Timestamptz
	LastVerified              pgtype.Timestamptz
	RecordedBy                int
	RecordedAt                pgtype.Timestamptz
}

type ServiceProvidingGroupProductApplicationHistory struct {
	ServiceProvidingGroupProductApplicationID int
	ID                                        int
	ServiceProvidingGroupID                   int
	ProcuringSystemOperatorID                 int
	ProductTypeID                             int
	Status                                    string
	Notes                                     *string
	LastPrequalified                          pgtype.Timestamptz
	LastVerified                              pgtype.Timestamptz
	RecordedBy                                int
	RecordedAt                                pgtype.Timestamptz
	ReplacedBy                                *int
	ReplacedAt                                pgtype.Timestamptz
}

type SystemOperatorProductType struct {
	ID               int
	SystemOperatorID int
	ProductTypeID    int
	Status           string
	RecordedBy       int
	RecordedAt       pgtype.Timestamptz
}

type SystemOperatorProductTypeHistory struct {
	SystemOperatorProductTypeID int
	ID                          int
	SystemOperatorID            int
	ProductTypeID               int
	Status                      string
	RecordedBy                  int
	RecordedAt                  pgtype.Timestamptz
	ReplacedBy                  *int
	ReplacedAt                  pgtype.Timestamptz
}

type TechnicalResource struct {
	ID                 int
	Name               string
	ControllableUnitID int
	Details            *string
	RecordedBy         int
	RecordedAt         pgtype.Timestamptz
}

type TechnicalResourceHistory struct {
	TechnicalResourceID int
	ID                  int
	Name                string
	ControllableUnitID  int
	Details             *string
	RecordedBy          int
	RecordedAt          pgtype.Timestamptz
	ReplacedBy          *int
	ReplacedAt          pgtype.Timestamptz
}
