// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package models

import (
	"context"
)

const entityLookup = `-- name: EntityLookup :one
SELECT
    entity_id::bigint,
    entity_found::boolean
FROM api.entity_lookup(
  $1::text,
  $2::text,
  $3::text,
  $4::text
)
`

type EntityLookupParams struct {
	EntityBusinessID     string
	EntityName           string
	EntityType           string
	EntityBusinessIDType string
}

type EntityLookupRow struct {
	EntityID    int
	EntityFound bool
}

func (q *Queries) EntityLookup(ctx context.Context, arg EntityLookupParams) (EntityLookupRow, error) {
	row := q.db.QueryRow(ctx, entityLookup,
		arg.EntityBusinessID,
		arg.EntityName,
		arg.EntityType,
		arg.EntityBusinessIDType,
	)
	var i EntityLookupRow
	err := row.Scan(&i.EntityID, &i.EntityFound)
	return i, err
}
