@startdot service_providing_group_status
digraph G {
    layout=dot;
    overlap=false;

    node [shape=rect, width=0.1, height=0.1, margin=0.04];
    nodesep=1;

    start [shape=point];

    // status
    new;
    {
        rank = same;
        inactive;
        active;
    }
    terminated [shape=oval];

    // transitions
    start -> new [label="", color="pink"];
    new -> active [label="", color="blue"];
    active -> inactive [label="", color="blue"];
    inactive -> active [label="", color="blue"];
    active -> terminated [label="", color="blue"];
   }
@enddot
