// Package accountingpoint provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package accountingpoint

import (
	"time"
)

const (
	Bearer_authScopes = "bearer_auth.Scopes"
)

// Defines values for EndUserEntityType.
const (
	Organisation EndUserEntityType = "organisation"
	Person       EndUserEntityType = "person"
)

// Defines values for EnergyDirectionDirection.
const (
	Both        EnergyDirectionDirection = "both"
	Consumption EnergyDirectionDirection = "consumption"
	Production  EnergyDirectionDirection = "production"
)

// AccountingPoint defines model for accounting_point.
type AccountingPoint struct {
	// EndUser Time-dependent list of end users associated with this accounting point
	EndUser []EndUser `json:"end_user"`

	// EnergyDirection Time-dependent list of energy directions associated with this accounting point
	EnergyDirection *[]EnergyDirection `json:"energy_direction,omitempty"`

	// EnergySupplier Time-dependent list of energy suppliers associated with this accounting point
	EnergySupplier []EnergySupplier `json:"energy_supplier"`

	// Gsrn Global Service Relation Number (GSRN) - unique identifier for the accounting point
	Gsrn string `json:"gsrn"`

	// MeteringGridArea Time-dependent list of metering grid areas associated with this accounting point
	MeteringGridArea []MeteringGridArea `json:"metering_grid_area"`
}

// EndUser defines model for end_user.
type EndUser struct {
	// BusinessId Business ID of the end user. Norwegian organization number or fødselsnummer, depending on `business_id_type``.
	BusinessId string `json:"business_id"`

	// EntityType Type of the end user entity, either a person or an organisation.
	EntityType *EndUserEntityType `json:"entity_type,omitempty"`

	// ValidFrom Start of the validity period
	ValidFrom time.Time `json:"valid_from"`

	// ValidTo End of the validity period
	ValidTo *time.Time `json:"valid_to"`
}

// EndUserEntityType Type of the end user entity, either a person or an organisation.
type EndUserEntityType string

// EnergyDirection defines model for energy_direction.
type EnergyDirection struct {
	// Direction Energy direction of the accounting point.
	Direction EnergyDirectionDirection `json:"direction"`

	// ValidFrom Start of the validity period
	ValidFrom time.Time `json:"valid_from"`

	// ValidTo End of the validity period
	ValidTo *time.Time `json:"valid_to"`
}

// EnergyDirectionDirection Energy direction of the accounting point.
type EnergyDirectionDirection string

// EnergySupplier defines model for energy_supplier.
type EnergySupplier struct {
	// BusinessId Business ID of the energy supplier. GLN format - 13 digits starting with non-zero.
	BusinessId string `json:"business_id"`

	// ValidFrom Start of the validity period
	ValidFrom time.Time `json:"valid_from"`

	// ValidTo End of the validity period
	ValidTo *time.Time `json:"valid_to"`
}

// MeteringGridArea defines model for metering_grid_area.
type MeteringGridArea struct {
	// BusinessId Business ID of the metering grid area. EIC-Y format.
	BusinessId string `json:"business_id"`

	// ValidFrom Start of the validity period
	ValidFrom time.Time `json:"valid_from"`

	// ValidTo End of the validity period
	ValidTo *time.Time `json:"valid_to"`
}
