// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package no.elhub.flex.controllableunit.db

import java.time.LocalDate

data class FlexAccountingPoint (
  val id: Long,
  val businessId: String,
  val systemOperatorId: Long,
  val recordTimeRange: Any,
  val recordedBy: Long
)

data class FlexControllableUnit (
  val id: Long,
  val businessId: String,
  val name: String,
  val startDate: LocalDate?,
  val status: String,
  val regulationDirection: String,
  val maximumActivePower: java.math.BigDecimal,
  val isSmall: Boolean,
  val accountingPointId: Long,
  val additionalInformation: String?,
  val createdByPartyId: Long,
  val recordTimeRange: Any,
  val recordedBy: Long
)

data class FlexTechnicalResource (
  val id: Long,
  val name: String,
  val controllableUnitId: Long,
  val technology: List<String>,
  val category: List<String>,
  val maximumActivePower: java.math.BigDecimal,
  val deviceType: String,
  val make: String?,
  val model: String?,
  val businessId: String?,
  val businessIdType: String?,
  val additionalInformation: String?,
  val recordTimeRange: Any,
  val recordedBy: Long
)

