// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package no.elhub.flex.controllableunit.db

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

const val getControllableUnitsByCUOrAPBusinessId = """-- name: getControllableUnitsByCUOrAPBusinessId :one
SELECT coalesce(jsonb_agg(row_to_json(cu)), '[]'::jsonb)::jsonb
FROM (
         SELECT
             cu.id,
             cu.business_id::text,
             cu.name,
             cu.start_date,
             (
                 SELECT coalesce(jsonb_agg(row_to_json(tr)), '[]'::jsonb)
                 FROM (
                          SELECT tr.id, tr.name
                          FROM flex.technical_resource AS tr
                          WHERE tr.controllable_unit_id = cu.id
                      ) AS tr
             ) AS technical_resources
         FROM flex.controllable_unit AS cu
                  INNER JOIN flex.accounting_point AS ap
                             ON cu.accounting_point_id = ap.id
                                 AND coalesce(cu.business_id = nullIf(?::text, '')::uuid, true)
                                 AND coalesce(ap.business_id = nullIf(?::text, ''), true)
     ) as cu
"""

class QueriesImpl(private val conn: Connection) : Queries {

  @Throws(SQLException::class)
  override fun getControllableUnitsByCUOrAPBusinessId(controllableUnitBusinessId: String, accountingPointBusinessId: String): String? {
    return conn.prepareStatement(getControllableUnitsByCUOrAPBusinessId).use { stmt ->
      stmt.setString(1, controllableUnitBusinessId)
          stmt.setString(2, accountingPointBusinessId)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = results.getString(1)
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

}

