// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package no.elhub.flex.controllableunit.db

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

interface Queries {
  @Throws(SQLException::class)
  fun getControllableUnitsByCUOrAPBusinessId(controllableUnitBusinessId: String, accountingPointBusinessId: String): String?
  
}

