server {
    listen       8080;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # We have a custom default.conf to allow us to
    # include other config files inside the server block.
    # The rest of the file is stock config from the nginx image.
    include /etc/nginx/conf.d/server/*.conf;
}
